In [3]:
# Problem 1 
import numpy as np
from scipy import linalg as la

def QR_Decomp(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    Q = np.copy(A)
    R = np.zeros((n, n))
    for i in range(n):
        R[i, i] = la.norm(Q[:,i])
        Q[:, i] = Q[:, i]/R[i,i]
        for j in range(i+1, n):
            R[i,j] = np.dot(Q[:,j].T, Q[:,i])
            Q[:,j] = Q[:,j] - R[i, j] * Q[:,i]
    return Q, R

A =  np.random.random((6,4))
Q,R = la.qr(A, mode="economic")
print(Q)
print(R)

q, r = QR_Decomp(A)
print(q)
print(r)

[[-0.629398    0.04196193  0.3677098  -0.16570974]
 [-0.11244264 -0.57028534  0.43250314 -0.51086293]
 [-0.15470879 -0.42912427  0.03211846  0.67910538]
 [-0.44268901  0.26439034 -0.55525209 -0.33482029]
 [-0.16275412 -0.62909498 -0.59880083 -0.06317129]
 [-0.58721166  0.15232673  0.09915451  0.36644236]]
[[-1.55139674 -1.23850566 -1.68190818 -1.0867843 ]
 [ 0.         -1.16009949 -0.23420035 -0.81249163]
 [ 0.          0.         -0.3718177  -0.19488721]
 [ 0.          0.          0.          0.41856312]]
[[ 0.629398   -0.04196193 -0.3677098  -0.16570974]
 [ 0.11244264  0.57028534 -0.43250314 -0.51086293]
 [ 0.15470879  0.42912427 -0.03211846  0.67910538]
 [ 0.44268901 -0.26439034  0.55525209 -0.33482029]
 [ 0.16275412  0.62909498  0.59880083 -0.06317129]
 [ 0.58721166 -0.15232673 -0.09915451  0.36644236]]
[[ 1.55139674  1.23850566  1.68190818  1.0867843 ]
 [ 0.          1.16009949  0.23420035  0.81249163]
 [ 0.          0.          0.3718177   0.19488721]
 [ 0.          0.          0

In [6]:
# Problem 2
def abs_det(A):
    Q,R = la.qr(A, mode="economic")
    return abs(la.det(R))

det = abs_det(np.matrix([[1, 2], [3, 4]]))
print(det)

1.9999999999999984


In [7]:
# Problem 3
def back_sub(A, b):
    n = np.size(b)
    x = np.zeros_like(b)
    x[-1] = 1. / A[-1, -1] * b[-1]
    for i in xrange(n-2, -1, -1):
        x[i] = 1. / A[i, i] * (b[i] - np.sum(A[i, i+1:] * x[i+1:]))
    return x

def solve(A, b):
    Q, R = la.qr(A, mode="economic")
    y = np.dot(Q.T, b)
    x = back_sub(R, y)
    return x

In [8]:
# Problem 4
def QR_Decomp1(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    R = np.copy(A)
    Q = np.identity(m)
    for k in range(n):
        u = np.copy(R[k:,k])
        sign = lambda x: 1 if x >= 0 else -1
        u[0] = u[0] + sign(u[0]) * la.norm(u)
        u = u/la.norm(u)
        R[k:,k:] = R[k:,k:] - 2*np.outer(u, np.dot(u.T, R[k:,k:]))
        Q[k:, :] = Q[k:, :] - 2*np.outer(u, np.dot(u.T, Q[k:,:]))
    return Q.T, R

A = np.random.random((5, 3))
Q,R = la.qr(A) 
print(Q)
print(R)

q, r = QR_Decomp1(A)
print(q)
print(r)

[[-0.29743719  0.28363833  0.57974632 -0.69397015  0.11567218]
 [-0.21554214 -0.56754295  0.16418759 -0.13018276 -0.76650601]
 [-0.68999336  0.54714183 -0.19267015  0.30762894 -0.30461062]
 [-0.11332477 -0.13903653  0.73055942  0.6327011   0.18384393]
 [-0.61330201 -0.52796682 -0.2570949  -0.0806947   0.52201749]]
[[-1.13955719 -0.94133522 -0.92168772]
 [ 0.          0.27558288 -0.7907845 ]
 [ 0.          0.          0.78719058]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[[-0.29743719  0.28363833  0.57974632 -0.69397015  0.11567218]
 [-0.21554214 -0.56754295  0.16418759 -0.13018276 -0.76650601]
 [-0.68999336  0.54714183 -0.19267015  0.30762894 -0.30461062]
 [-0.11332477 -0.13903653  0.73055942  0.6327011   0.18384393]
 [-0.61330201 -0.52796682 -0.2570949  -0.0806947   0.52201749]]
[[ -1.13955719e+00  -9.41335220e-01  -9.21687719e-01]
 [  2.77555756e-17   2.75582879e-01  -7.90784500e-01]
 [  1.11022302e-16   1.38777878e-17   7.87190583e-01]
 [  0.0000

In [15]:
# Problem 5
def Hessenberg(A):
    m = np.shape(A)[0]
    n = np.shape(A)[1]
    H = np.copy(A)
    Q = np.identity(m)
    for k in range(n-2):
        u = np.copy(H[k+1:,k])
        sign = lambda x: 1 if x >= 0 else -1
        u[0] = u[0] + sign(u[0]) * la.norm(u)
        u = u/la.norm(u)
        H[k+1:,k:] = H[k+1:,k:] - 2*np.outer(u, np.dot(u.T, H[k+1:,k:]))
        H[:, k+1:] = H[:, k+1:] - 2*np.outer(np.dot(H[:, k+1:], u), u.T)
        Q[k+1:,k:] = Q[k+1:,k:] - 2*np.outer(u, np.dot(u.T, Q[k+1:,k:]))
    return H, Q.T

A = np.random.random((8,8))
H, Q = la.hessenberg(A, calc_q=True)
print(H)
print(Q)
h, q = Hessenberg(A)
print(h)
print(q)

[[  2.75863071e-01  -1.34760827e+00  -1.20879085e+00  -1.68877599e-01
    1.20139380e-01   1.48923984e-03   1.65313209e-01  -1.49828261e-01]
 [ -1.48514024e+00   2.81775367e+00   1.48022485e+00   3.85681687e-01
    3.53272746e-01   6.03423755e-01  -5.58471752e-01  -2.17654492e-01]
 [  0.00000000e+00   1.94042406e+00   4.09928916e-01   1.10203540e-01
   -7.63518403e-02   2.37157790e-01   8.22914999e-02  -7.29427974e-02]
 [  0.00000000e+00   0.00000000e+00   5.73761863e-01   3.81419484e-01
    3.65691593e-01   1.85812729e-01  -2.62474900e-01   2.04033547e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00  -4.26450752e-01
    1.94495213e-03   2.74695505e-01  -1.62671297e-01  -6.65344838e-02]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    6.74327754e-01  -4.64700242e-01  -2.86965591e-01  -2.51335677e-01]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   2.10845923e-01   8.84330939e-02  -2.77706776e-01]
 [  0.0000000