In [1]:
# Problem 1
import numpy as np
from scipy.sparse import dok_matrix
    
def adj_mat(name, N):
    int_mat = []
    with open(name, 'r') as myfile:
        l = [line.strip().split() for line in  myfile.read().splitlines()[1: ]]
        int_mat.append(l)
        int_mat = np.array(int_mat).astype(int)
        int_mat = int_mat[0]
        mat = dok_matrix((N, N), dtype=int)
        try:
            for i in range(int_mat.shape[0]):
                mat[int_mat[i][0], int_mat[i][1]] = 1
        except:
            np.unique(int_data) != N
            raise ValueError
    return mat      

In [4]:
# Problem 2
from numpy.linalg import inv
def tran_mat(m):
    Am = np.copy(m)
    D = np.zeros_like(Am)
    for i in range(m.shape[0]):
        if all(Am[i, :] == 0):
            Am[i, :] = np.ones(m.shape[0])
        D[i, i] = np.sum(Am[i, :])
    K = np.dot(np.transpose(Am), inv(D))
    return K

In [6]:
# Testing with the given matrix
m = adj_mat('matrix.txt', 8)
m = m.todense()
tran_mat(m)

array([[ 0.        ,  1.        ,  0.125     ,  0.33333333,  0.33333333,
         0.5       ,  1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.33333333,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.        ,  0.33333333,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.125     ,  0.33333333,  0.33333333,
         0.5       ,  0.        ,  0.        ],
       [ 1.        ,  0.        ,  0.125     ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]])

In [38]:
# Problem 3
def iterative(A, N = None, d = 0.85, tol = 1e-5):
    if N != None:
        adj = np.copy((A[:N, :N]))
    else:
        N = int(A.shape[0])
        adj = np.copy(A)
    p0 = np.full(N, 1/N) 

    K = tran_mat(adj)
    max_iter = 3000
    ite = 1
    dist = 1 
    while ite < max_iter and dist > tol:
        p1 = np.copy(p0)
        p0 = np.dot( d * K, p0) + (1 - d)/ N
        p = p1 - p0
        dist = max(abs(x) for x in p)
        ite += 1
    return p1

In [39]:
iterative(m)

array([ 0.43869813,  0.02171029,  0.02786154,  0.02171029,  0.02171029,
        0.02786154,  0.04585394,  0.39459399])

In [66]:
# Problem 4
from scipy import linalg as la
def eigenvalue(A, N = None, d = 0.85):
    if N != None:
        adj = np.copy((A[:N, :N]))
    else:
        N = int(A.shape[0])
        adj = np.copy(A)
    K = tran_mat(adj)
    P = d * K + (1 - d)/ N
    v = la.eig(P.T, left = True)[1][:,0]
    v = (v/v.sum())
    return v

In [67]:
eigenvalue(m)

array([ 0.43869288-0.j,  0.02171029-0.j,  0.02786154-0.j,  0.02171029-0.j,
        0.02171029-0.j,  0.02786154-0.j,  0.04585394-0.j,  0.39459924-0.j])

In [80]:
# Problem 5
import pandas as pd
data = pd.read_csv('ncaa2013.csv', skiprows = 1, index_col=False).astype(str)
data = data.values
m = np.shape(data)[0]
team, index = np.unique(data, return_inverse=True)
index = index.reshape(m, 2)
adj = np.zeros((len(team) , len(team)))
for i in range(m):
    adj[index[i, 1], index[i, 0]] = 1

p = iterative(adj, d = 0.7)
r = np.argsort(p)[::-1]
r = team[r]
print(r[: 5])

['Duke' 'Butler' 'Louisville' 'Illinois' 'Indiana']
