In [20]:
import numpy as np
A = np.array([[1, -1], [3, 1], [4, 3]])
b = np.array([2, 5, 7])
c = np.array([3, 2])

# Problem 1
def check_origin(c, A, b):
    if any(b < 0)==True:
        raise ValueError
    else:
        pass

check_origin(c, A, b)

In [21]:
# Problem 2
def index_list(A):
    m, n = A.shape
    a = np.arange(n, n + m)
    b = np.arange(0, n)
    L = np.hstack([a, b])
    L = np.ndarray.tolist(L)
    return L

L = index_list(A)
print(L)

[2, 3, 4, 0, 1]


In [22]:
# Problem 3
def tableau(c, A, b):
    ''' c - 1*n
        A - m*n
        b - 1*n
    '''
    m, n = A.shape
    c_bar = np.concatenate([c, np.zeros(m)])
    c_bar1 = -1 * c_bar
    A_bar = np.concatenate([A, np.eye(m)], axis = 1)
    T1 = np.concatenate([np.array([0]), c_bar1, np.array([1])])
    T2 = np.hstack([b.reshape(len(b), 1), A_bar, np.zeros((m, 1))])
    T = np.vstack([T1, T2])
    return T

T = tableau(c, A, b)
print(T)

[[ 0. -3. -2. -0. -0. -0.  1.]
 [ 2.  1. -1.  1.  0.  0.  0.]
 [ 5.  3.  1.  0.  1.  0.  0.]
 [ 7.  4.  3.  0.  0.  1.  0.]]


In [23]:
# Problem 4
def pivot(T):
    p, q = T.shape
    T1 = T[0, 1:]
    column = np.where(T1 < 0)[0][0] + 1
    if all(T[:, column] <= 0)== True:
        raise ValueError
    else:
        find_positive = np.where(T[:, column] > 0)[0]
        mat = np.zeros(len(find_positive)) #initialize matrix for calculating ratio
        for i in range(len(find_positive)):
            mat[i] = float(T[find_positive[i], 0]/T[find_positive[i], column])
        m = np.where(mat==min(mat))[0][0]
        row = find_positive[m]
        
    return row+1, column+1 

pivot(T)

(3, 2)

In [24]:
# Problem 5
def operation(T, L):
    T_new = np.copy(T)
    m, n = pivot(T)
    a, b = m - 2, L.index(n - 2) # tracking variables
    p, q = T.shape
    m = m - 1
    n = n - 1
    if T[m, n] == 0:
        T_new[m,:] = T[m, :]
    else:
        T_new[m,:] = T[m, :]/float(T[m, n])
    for i in range(p):
        if i == m or T[i, n] == 0:
            T_new[i, :] = T_new[i, :]
        else:
            T_new[i, :] = T_new[i, :] - float((T_new[i, n]/T_new[m, n])) * T_new[m, :]
    L[a], L[b] = L[b], L[a]
    return T_new, L

operation(T, L)

(array([[ 5.        ,  0.        , -1.        ,  0.        ,  1.        ,
          0.        ,  1.        ],
        [ 0.33333333,  0.        , -1.33333333,  1.        , -0.33333333,
          0.        ,  0.        ],
        [ 1.66666667,  1.        ,  0.33333333,  0.        ,  0.33333333,
          0.        ,  0.        ],
        [ 0.33333333,  0.        ,  1.66666667,  0.        , -1.33333333,
          1.        ,  0.        ]]), [2, 0, 4, 3, 1])

In [25]:
# Problem 6
def solve(T_old, L_old):
    tol = -1e-10
    while any(T_old[0, 1:] < tol) == True:
        T_new, L_new = operation(T_old, L_old)
        T_old = np.copy(T_new)
        L_old = L_new
    values1 = np.ndarray.tolist(T_old[1:,0])
    D1 = dict(zip(L_old[:len(values1)], [float(str(round(i, 2))) for i in values1]))
    D2 = dict(zip((L_old[len(values1):]), np.zeros(len(L_old) - len(values1))))
    return float(T_old[0,0]), D1, D2

print(solve(T, L))

(5.2, {2: 0.6, 0: 1.6, 1: 0.2}, {3: 0.0, 4: 0.0})


In [26]:
# Problem 7
data = np.load('/Users/Sophia/Downloads/productMix.npz')
A = data['A']
p = data['p']
m = data['m']
d = data['d']
print(A)
print(p)
print(m)
print(d)

[[ 0.12  0.18  0.13  0.07]
 [ 0.15  0.12  0.13  0.11]
 [ 0.1   0.1   0.1   0.12]]
[ 250.  215.  275.  180.]
[ 4.  4.  4.]
[ 10.  20.  12.  10.]


In [27]:
A = np.vstack([A, np.eye(4)])
b = np.hstack([m, d])
L = index_list(A)
T = tableau(p, A, b)
solve(T, L)

(7453.596491228071,
 {0: 10.0, 1: 6.19, 2: 12.0, 3: 1.79, 6: 0.97, 8: 13.81, 10: 8.21},
 {4: 0.0, 5: 0.0, 7: 0.0, 9: 0.0})